# Generated by Django 5.2.15 on 2026-06-20 17:17

import django.db.models.deletion
import workmanager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workmanager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workmanager.documentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to=workmanager.models.document_upload_path)),
                ('external_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('freelance_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workmanager.freelancesource')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workmanager.job')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workmanager.project')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='workmanager.documentcategory')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('plain', 'Plain'), ('points', 'Point Wise'), ('table', 'Table'), ('checklist', 'Checklist'), ('custom', 'Custom')], default='plain', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('will_start', 'Will Start'), ('started', 'Started'), ('partial_done', 'Partial Done'), ('almost_done', 'Almost Done'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='will_start', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('freelance_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_records', to='workmanager.freelancesource')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_records', to='workmanager.job')),
                ('members', models.ManyToManyField(blank=True, related_name='note_records', to='workmanager.workmember')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_records', to='workmanager.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['owner', 'is_active'], name='workmanager_owner_i_863b53_idx'),
        ),
        migrations.AddIndex(
            model_name='documentcategory',
            index=models.Index(fields=['owner', 'parent'], name='workmanager_owner_i_cbb5c1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('owner', 'parent', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'category', 'is_active'], name='workmanager_owner_i_bef1fa_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'job', 'project'], name='workmanager_owner_i_afa6c3_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'status', 'data_type', 'is_active'], name='workmanager_owner_i_e3de07_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['owner', 'job', 'project'], name='workmanager_owner_i_a98671_idx'),
        ),
    ]
