# Generated by ChatGPT update: member source linking.
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workmanager", "0002_working_days_email_variables"),
    ]

    operations = [
        migrations.AddField(
            model_name="workmember",
            name="source_type",
            field=models.CharField(
                choices=[("job", "Job"), ("freelancing", "Freelancing"), ("manual", "Manual / Other")],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workmember",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="workmanager.job",
            ),
        ),
        migrations.AddField(
            model_name="workmember",
            name="freelance_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="workmanager.freelancesource",
            ),
        ),
    ]
