# Generated by ChatGPT update: email variable master table.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workmanager", "0003_member_source_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVariable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(help_text="Variable key used in templates, for example name or project_name.", max_length=80)),
                ("label", models.CharField(help_text="User-friendly label shown in the template builder.", max_length=120)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(choices=[("common", "Common"), ("person", "Person / Recipient"), ("job", "Job"), ("project", "Project"), ("task", "Task"), ("meeting", "Meeting / MOM"), ("leave", "Leave"), ("salary", "Salary / Payment"), ("custom", "Custom")], default="custom", max_length=20)),
                ("default_value", models.CharField(blank=True, help_text="Optional fallback/example value shown while composing email.", max_length=250)),
                ("is_required", models.BooleanField(default=False, help_text="Ask this value before sending when used in a template.")),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="%(class)s_items", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["category", "label"],
                "unique_together": {("owner", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="emailvariable",
            index=models.Index(fields=["owner", "category", "is_active"], name="workmanager_owner_i_7c5f5f_idx"),
        ),
    ]
