# Generated by ChatGPT for MOM action point support
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workmanager", "0004_email_variables_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="action_items",
            field=models.JSONField(blank=True, default=list, help_text="Point-wise MOM actions: [{text, status}]."),
        ),
    ]
